all:
	$(MAKE) -C parallel_code
	$(MAKE) -C serial_code
	$(MAKE) -C rgb_code

clean:
	$(MAKE) -C rgb_code clean
	$(MAKE) -C serial_code clean
	$(MAKE) -C parallel_code clean
	$(MAKE) -C simple-jpeg clean
